### ISSUE TITLE
ROOT 5 Incompatibility?

### ISSUE THREAD

**Issue by twongjirad** [LArbys/LArCV#1]
Error messages from compilation.

But do we care?  I am upgrading to 6 as we speak (and fly)

In file included from /Users/twongjirad/working/larbys/LArCV/core/build/Base/BaseDict.cxx:20:
In file included from /Users/twongjirad/software/root_v5.34.34/include/TClass.h:42:
/Users/twongjirad/software/root_v5.34.34/include/ThreadLocalStorage.h:228:4: error: thread-local storage is not supported for the current target
TTHREAD_TLS(T_) ptr = NULL;
^
/Users/twongjirad/software/root_v5.34.34/include/ThreadLocalStorage.h:103:29: note: expanded from macro 'TTHREAD_TLS'
#  define TTHREAD_TLS(type) thread_local type
                            ^
/Users/twongjirad/software/root_v5.34.34/include/ThreadLocalStorage.h:229:4: error: thread-local storage is not supported for the current target
TTHREAD_TLS(Bool_t) isInit(kFALSE);
 ^
/Users/twongjirad/software/root_v5.34.34/include/ThreadLocalStorage.h:103:29: note: expanded from macro 'TTHREAD_TLS'
#  define TTHREAD_TLS(type) thread_local type
                            ^
/Users/twongjirad/software/root_v5.34.34/include/ThreadLocalStorage.h:239:4: error: thread-local storage is not supported for the current target
TTHREAD_TLS(Array_) ptr = NULL;
   ^
/Users/twongjirad/software/root_v5.34.34/include/ThreadLocalStorage.h:103:29: note: expanded from macro 'TTHREAD_TLS'
#  define TTHREAD_TLS(type) thread_local type
                            ^
/Users/twongjirad/software/root_v5.34.34/include/ThreadLocalStorage.h:240:4: error: thread-local storage is not supported for the current target
TTHREAD_TLS(Bool_t) isInit(kFALSE);
^
/Users/twongjirad/software/root_v5.34.34/include/ThreadLocalStorage.h:103:29: note: expanded from macro 'TTHREAD_TLS'
#  define TTHREAD_TLS(type) thread_local type
                            ^
/Users/twongjirad/software/root_v5.34.34/include/ThreadLocalStorage.h:250:4: error: thread-local storage is not supported for the current target
TTHREAD_TLS(T_) ptr = NULL;
^
/Users/twongjirad/software/root_v5.34.34/include/ThreadLocalStorage.h:103:29: note: expanded from macro 'TTHREAD_TLS'
#  define TTHREAD_TLS(type) thread_local type
                            ^
/Users/twongjirad/software/root_v5.34.34/include/ThreadLocalStorage.h:251:4: error: thread-local storage is not supported for the current target
TTHREAD_TLS(Bool_t) isInit(kFALSE);
^
/Users/twongjirad/software/root_v5.34.34/include/ThreadLocalStorage.h:103:29: note: expanded from macro 'TTHREAD_TLS'
#  define TTHREAD_TLS(type) thread_local type
                            ^
6 errors generated.
make[1]: *_\* [/Users/twongjirad/working/larbys/LArCV/core/build/Base/BaseDict.o] Error 1

**Comment by twongjirad** [comment]
All solved by using ROOT 6.

**Comment by drinkingkazu** [comment]
But using a better software to solve a problem is totally anti-lartpc spirit. I'll work on this...

**Comment by drinkingkazu** [comment]
I did not see the same error, but now larcv works w/ ROOT5 that's used by larsoft at least.
If more erros remaining please let me know!
