### ISSUE TITLE
Support for more than 3 channels

### ISSUE THREAD

**Issue by twongjirad** [LArbys/LArCV#15]
Specific example is the 12 channel data used in the previous neutrino ID network.  Channels go (TPC image, pmt weighted, MIP channels, HIP channels) x 3 planes.

I imagine that we will have many combinations of channels.

**Comment by vgenty** [comment]
**note** 

add a dropdown menu that allows you to select the channel to be put into the RGB channels

**Comment by twongjirad** [comment]
proposal for implementation here: https://github.com/LArbys/LArCV/pull/19

@vgenty: it's totally cool to reject them.

**Comment by vgenty** [comment]
support added, this considering how to label R,G,B dropdown will leave it for now

https://github.com/LArbys/LArCV/commit/abb42a2710d1c88b6b6f392ef1855bdf10da5448
