### ISSUE TITLE
viewer caffe forward computation to use new implementation

### ISSUE THREAD

**Issue by drinkingkazu** [LArbys/LArCV#23]
We want to run the viewer with exactly same way image is passed onto the network training and/or forward computation. 
New branch: https://github.com/LArbys/caffe/tree/process_driver/src/caffe
... has the implementation we planed already in place.

need this to be implemented in view_rgb.py

**Comment by vgenty** [comment]
Yes, I've reviewed APICaffe in LArCV and your caffe branch which loads via the thread factory. I don't know your exact configuration for SimpleFiller (maybe you can point me to it) but I assume I can let pycaffe create a ROOTLayer then access the instantiated [SimpleFiller](https://github.com/LArbys/LArCV/blob/master/app/APICaffe/SimpleFiller.cxx`) and call [fill_entry_data](https://github.com/LArbys/LArCV/blob/master/app/APICaffe/SimpleFiller.cxx#L134) bypassing the need for a ROOT file on disk.

**Comment by drinkingkazu** [comment]
Given ROOT data layer caffe config looking like this:

layer {
  name: "data"
  type: "ROOTData"
  top: "data"
  top: "label"

  root_data_param {
    batch_size: 1
    filler_config: "ana_filler.cfg"
    filler_name: "Analysis"
  }  
}

... to process 1 event at a time, here's how filler config looks like

Analysis: {
  Verbosity:    2
  EnableFilter: false
  RandomAccess: false

  InputFiles:   ["/stage/drinkingkazu/production/v03/hires_crop/data_extbnb/part01/hiresdiv_extbnb_0000_0009.root","/stage/drinkingkazu/production/v03/hires_crop/data_extbnb/part01/hiresdiv_extbnb_0010_0019.root","/stage/drinkingkazu/production/v03/hires_crop/data_extbnb/part01/hiresdiv_extbnb_0020_0039.root","/stage/drinkingkazu/production/v03/hires_crop/data_extbnb/part01/hiresdiv_extbnb_0040_0059.root","/stage/drinkingkazu/production/v03/hires_crop/data_extbnb/part01/hiresdiv_extbnb_0060_0079.root","/stage/drinkingkazu/production/v03/hires_crop/data_extbnb/part01/hiresdiv_extbnb_0080_0099.root","/stage/drinkingkazu/production/v03/hires_crop/data_extbnb/part01/hiresdiv_extbnb_0100_0119.root","/stage/drinkingkazu/production/v03/hires_crop/data_extbnb/part01/hiresdiv_extbnb_0140_0159.root","/stage/drinkingkazu/production/v03/hires_crop/data_extbnb/part01/hiresdiv_extbnb_0160_0180.root"]

  ProcessType:  ["SimpleFiller"]
  ProcessName:  ["SimpleFiller"]

  ProcessList: {
    SimpleFiller: {
      # DatumFillerBase configuration
      MeanADC:           [0,0,0]
      MeanImageFile:     "/stage/drinkingkazu/production/v03/hires_crop/data_extbnb/mean_part01.root"
      MeanImageProducer: "mean"
      InputProducer:     "tpc_hires_crop"
      ROIProducer:       "tpc_hires_crop"
      # SimpleFiller configuration
      Channels:          []
      MaxADC:            [200,200,200]
      MinADC:            [17,13,20]
      GausSmearingMean:  1.0
      GausSmearingSigma: 0.1
      PixelWiseSmearing: true
    }
  }
}

**Comment by drinkingkazu** [comment]
I think this is a legacy feature so I would close. But please re-open if needed!
