### ISSUE TITLE
ADC threshold values in the viewer

### ISSUE THREAD

**Issue by drinkingkazu** [LArbys/LArCV#28]
The "default" ADC thresholds in the viewer might be better fetched from actual min/max ADC value from pixels in the image.

Then whether updating it or not per event should be probably an option to pick for a user (so a user can "freeze" the threshold going one event to the next).

**Comment by vgenty** [comment]
preliminary implementation in place here i can push to master whenever we are ready https://github.com/LArbys/LArCV/commit/63e5eb5b18bf73ada0fabab0b15e35d9404e7f51

will make it default to the min/max ADC, currently default is to the user. Will change

update: https://github.com/LArbys/LArCV/commit/d98464cc7bcd598397ef3bf6cdba28277537a8cf
