### ISSUE TITLE
APICaffe: if requested by user, put entry number into top blob

### ISSUE THREAD

**Issue by twongjirad** [LArbys/LArCV#30]
otherwise don't.

This is for analyses.  This way they can run forward() with ROOT random access and have a way to get entry info without having to figure out way to align trees.

During training, will probably not want to load this info into top blob.

**Comment by drinkingkazu** [comment]
For now, you can access processed entries through ThreadFillerFactory which holds an instance used by caffe. 

larcv.ThreadFillerFactory.get("Train")

should return ThreadDatumFiller instance used by caffe if "Train" is the name assigned for a filler (this is prototxt configuration).

We can add more into Datum but the more variables we want to expose, probably it's better to use organized data structure than 1D array datum. Flexible analysis variable filling into a struct or something could be an future extension!
