### ISSUE TITLE
In ThreadFiller have a repeat batch function

### ISSUE THREAD

**Issue by twongjirad** [LArbys/LArCV#34]
This way averages of a batch can be taken more easily.  Right now for random access mode, can't repeat by simply specifying first entry.

**Comment by drinkingkazu** [comment]
This is now possible by https://github.com/LArbys/LArCV/commit/29ea5ed78475c6656c9f68410962cb10d1ecb6aa

One can specify a set of TTree indecies to be used in the next batch. The "last batch" can be retrieved back via existing function.
