### ISSUE TITLE
ROI Feature musings

### ISSUE THREAD

**Issue by twongjirad** [LArbys/LArCV#40]
I am going to make a note of desired features/bugs of my first tests of the roi feature (thanks vic!).

**Comment by twongjirad** [comment]
1) if one tries to write the roi twice program barfs [FIXED]
2) add option to fix 3 plane ROIs to the same time [DONE -- tmw_roi_feature branch]
3) have little indicator showing (wire,time) coordinates of at least Y-plane [DONE] -- but placement is bad
4) roi tree should store run, subrun, event [OPTION ADDED]
5) unclear if ROI info stored [DONE] -- it's stored, I'm just stupid.
6) I can make an infinite amount of ROIs.  Is this OK? [YES]
7) Have a check box that helps store in ROI if ROI is crap.  For when algorithm ends up finding some oddity. We want to be able to remove these from the ROI list.  Of course, maybe we just wouldn't save an ROI for an event. But how will this affect the LArCV iomanager to have a missing entry like that... [DONE]

**Comment by vgenty** [comment]
Thanks!

For 1) never tested this
for 2) it can be implemented

Will work on this a bit today

**Comment by twongjirad** [comment]
I'm making modifcations to the roi feature tool on tmw_roi_feature.  Vic, please pull if you like the mods.

**Comment by vgenty** [comment]
OK will review after a meeting

**Comment by twongjirad** [comment]
implemented same time feature option.  also fixed the issue where the box sizes are not adjusted without first bumping them. the python barf you were seeing was an infinite loop.  when one box was resized, it resized the others, which resized the others, and so forth.  set optional argument finish=False to avoid incepting bounding boxes.

**Comment by twongjirad** [comment]
also, i put check box options i would like. but i put them randomly in your ROI layout. Please re-arrange them as you see fit.

**Comment by vgenty** [comment]
Yeah I noticed this, the only way around the inf loop I saw is to bump the boxes before resize. Thanks for finding the solution!

**Comment by twongjirad** [comment]
I think we achieved all of the above!
