### ISSUE TITLE
saving ROI content as a picture

### ISSUE THREAD

**Issue by erezcoh4** [LArbys/LArCV#52]
In order to make manual-scan easier, I thought of looping over the larcv-events and plotting 3-images with the three ROIs contents, where the ROIs are given their initial values from our list of GBDT candidates. 
Does this make sense?

**Comment by drinkingkazu** [comment]
@erezcoh4 so the viewer has a capability to show ROI already. Do I understand it right that you want to show image-just-inside-ROI automatically?

If that is the case, 2 possible solutions I can think of:

0) Make that as a viewer feature (i.e. enable auto-focus mode that shows inside ROI by default when moving one event to another)

1) Run a cropper module to crop ROI region from an image

We want a module like 1) whether we choose that for this particular request or not imho. It is a handy module. I just cannot remember if we have such module.

**Comment by erezcoh4** [comment]
I'll be glad to go with option 1 and run a cropper. I tried to look for examples on-line but couldn't manage to implement them on the display layout

**Comment by drinkingkazu** [comment]
OK so I just wanted to point out you should have this feature w/ 0) if you want it right away.
I am happy to be in charge of 1).

**Comment by erezcoh4** [comment]
thanks
i'd be glad to then learn how you implemented it, whenever you have time to teach me

**Comment by drinkingkazu** [comment]
OK after discussing w/ Taritree this morning making a chain work to produce cropped-ROI-image for proton sample is on my to-do list. I just pushed CropROI module that works w/ unit testing.
https://github.com/LArbys/LArCV/commit/e41e0c586026827ebb872f09bbaa85aa3e988883
