### ISSUE TITLE
Make the 1st release candidate

### ISSUE THREAD

**Issue by drinkingkazu** [LArbys/LArCV#56]
... at least I want to make an attempt to get an agreement.

a) Use git flow release
b) Versioning convention, I propose typical 3 level versioning vXX.YY.ZZ where...
    b-1) Increment ZZ for completely backward-compatible release
    b-2) Increment YY for partially backward-compatible module, defined as backward incompatibility outside "core" directory (so a change in module configuration format, caffe interface, etc)
    b-3) Increment XX for backward incompatible change in "core"

The current (initial) motivation is to push out the current develop https://github.com/LArbys/LArCV/commit/29ea5ed78475c6656c9f68410962cb10d1ecb6aa that is still backward compatible with the caffe configuration used for long by now.

**Comment by drinkingkazu** [comment]
Candidate is here: https://github.com/LArbys/LArCV/tree/release/v01.00.00

**Comment by twongjirad** [comment]
hmm, has the boat sailed on this?

**Comment by drinkingkazu** [comment]
no the boat exploded but we can re-try :)

**Comment by drinkingkazu** [comment]
I believe this is done.
