### ISSUE TITLE
PyObject* ThreadDatumFiller::data_ndarray() was removed.

### ISSUE THREAD

**Issue by twongjirad** [LArbys/LArCV#60]
This function is used by those working with TensorFlow.

Needs to be restored and made compatible with latest changes.

**Comment by drinkingkazu** [comment]
Sorry! but the logic was to separate a dependency. This function shouldn't have to be in APICaffe imho. Can we move it to PyUtil? It made debugging on compilation / unit testing easier where Python support does not exist (i.e. various machines).

**Comment by drinkingkazu** [comment]
... and in fact this is already done when commit was made. The dependency was decoupled into PyUtil:
https://github.com/LArbys/LArCV/commit/901050567e2f2db01adf7a81d74ca740a8c7af3b

**Comment by twongjirad** [comment]
Thanks, for pointing that out to me. Yes, that function works.
