### ISSUE TITLE
segmentation image not showing up in v05 production!

### ISSUE THREAD

**Issue by drinkingkazu** [LArbys/LArCV#68]
@twongjirad reported segmentation image is not stored in v05 output larcv file.
I confirmed this independently upon his report.
Bug is believed to be within supera.

**Comment by drinkingkazu** [comment]
The problem was due to time offset now being different in both MC and reco. It is now fixed: https://github.com/LArbys/LArCV/commit/2fd261ef5d56657efc5bb75fe1893036cca9901c

TimeOffset parameter in Supera is now solely for reco-wire object and not for MC (simchannel).

**Comment by twongjirad** [comment]
orz
