### ISSUE TITLE
rgb viewer: dynamic adc rescaling/smearing 

### ISSUE THREAD

**Issue by drinkingkazu** [LArbys/LArCV#7]
We want to "choose a range, modify ADC value" functionality.
To get started with, pixel-by-pixel gaussian scaling/smearing would be fine (generate gaussian random draw for specified mean & sigma + multiply to pixel value, performed per pixel)

**Comment by vgenty** [comment]
consolidating @ https://github.com/LArbys/LArCV/issues/13
