### ISSUE TITLE
rgb viewer: caffe forward computation

### ISSUE THREAD

**Issue by drinkingkazu** [LArbys/LArCV#8]
combined with #7 we want to perform caffe.Net forward computation after changing ADC values... to inspect how probability may change.

**Comment by vgenty** [comment]
progress made in rgb_caffemod branch, rudimentary mean file loading, thresholding, works on my fake color nu alex validation sample. No instructions yet but to make sure prototxt is deploy

https://github.com/LArbys/LArCV/commit/d086df734f0f34ddb1a69a86559d0a852d0c68ea
<img width="1312" alt="config" src="https://cloud.githubusercontent.com/assets/5595000/14940456/9e25028a-0f3b-11e6-81c5-dae612f3fe54.png">

**Comment by vgenty** [comment]
I have it working in https://github.com/LArbys/LArCV/tree/rgb_caffemod so I will close. See new issue

https://github.com/LArbys/LArCV/issues/13

for feature request

**Comment by vgenty** [comment]
I'm going to close, this for now... basic functionality is there
