### ISSUE TITLE
develop branch missing DataFormat/ParticleMass.h

### ISSUE THREAD

**Issue by twongjirad** [LArbys/LArCV#82]
app/Filter/CCQETruthFilter.cxx requires it.  Stopping the build from finishing.

**Comment by drinkingkazu** [comment]
done @ c7d037c3e213b318fd83745ae45c0f5121dbbc80

**Comment by drinkingkazu** [comment]
But I do get a compiler error that looks like a compiler version issue while building DBSCANN algorithm:

In file included from DBSCANAlgo.cxx:3:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/algorithm:62:
/usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/bits/stl_algo.h:2263:11: error: no matching function for call to object of type 'mycompare_t'
          while (__comp(*__first, __pivot))
                 ^~~~~~
/usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/bits/stl_algo.h:2296:19: note: in instantiation of function template specialization
      'std::__unguarded_partition<__gnu_cxx::__normal_iterator<std::pair<int, double> *, std::vector<std::pair<int, double>, std::allocator<std::pair<int, double> > > >,
      std::pair<int, double>, mycompare_t>' requested here
      return std::__unguarded_partition(__first + 1, __last, *__first, __comp);
                  ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/bits/stl_algo.h:2337:11: note: in instantiation of function template specialization
      'std::__unguarded_partition_pivot<__gnu_cxx::__normal_iterator<std::pair<int, double> *, std::vector<std::pair<int, double>, std::allocator<std::pair<int, double> > > >,
      mycompare_t>' requested here
            std::__unguarded_partition_pivot(__first, __last, __comp);
                 ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/bits/stl_algo.h:5498:9: note: in instantiation of function template specialization
      'std::__introsort_loop<__gnu_cxx::__normal_iterator<std::pair<int, double> *, std::vector<std::pair<int, double>, std::allocator<std::pair<int, double> > > >, long,
      mycompare_t>' requested here
          std::__introsort_loop(__first, __last,
               ^
DBSCANAlgo.cxx:264:12: note: in instantiation of function template specialization 'std::sort<__gnu_cxx::__normal_iterator<std::pair<int, double> *, std::vector<std::pair<int,
      double>, std::allocator<std::pair<int, double> > > >, mycompare_t>' requested here
      std::sort( hitlist.begin(), hitlist.end(), mycompare );
           ^
DBSCANAlgo.cxx:221:12: note: candidate function not viable: 2nd argument ('const std::pair<int, double>') would lose const qualifier
      bool operator() ( std::pair<int,double>& lhs, std::pair<int,double>& rhs ) { 
           ^
In file included from DBSCANAlgo.cxx:3:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/algorithm:62:

**Comment by vgenty** [comment]
Same result as above on develop with GCC 4.8.4 on ubuntu 14.04.5

https://goo.gl/Uj8ZCE

**Comment by twongjirad** [comment]
thanks guys!  moving this new issue into its own record #84
