### ISSUE TITLE
error: no class named 'CircularBufferBase' in namespace 'larcv'

### ISSUE THREAD

**Issue by twongjirad** [LArbys/LArCV#83]
Compiling APICaffe...
    make[1]: Entering directory '/home/twongjirad/working/larcv/app/APICaffe'
    << generating dict >>
    In file included from input_line_12:7:
    ./CircularBufferBase.imp.h:4:23: error: explicit instantiation of non-template class 'CircularBufferBase'
    template class larcv::CircularBufferBase<std::vector<double> >;
                          ^                 ~~~~~~~~~~~~~~~~~~~~~~
    ./CircularBufferBase.imp.h:4:23: error: no class named 'CircularBufferBase' in namespace 'larcv'
    template class larcv::CircularBufferBase<std::vector<double> >;
                   ~~~~~~~^
    Error: rootcling: compilation failure     (/home/twongjirad/working/larcv/build/lib/libLArCVAPICaffe3f4dfb8768_dictUmbrella.h)
     /home/twongjirad/working/larcv/Makefile/GNUmakefile.CORE:41: recipe for target '/home/twongjirad/working/larcv/build/APICaffe/APICaffeDict.cxx' failed
    make[1]: *** [/home/twongjirad/working/larcv/build/APICaffe/APICaffeDict.cxx] Error 1
    make[1]: Leaving directory '/home/twongjirad/working/larcv/app/APICaffe'

develop won't build.

**Comment by twongjirad** [comment]
"fixed this" by adding header to imp.h file.  done here: https://github.com/LArbys/LArCV/commit/2b60f46c0d98c49fe347a648cb147d8cf3b554ab

would like @drinkingkazu to maybe check that this is OK with intended use, before issue closed.

**Comment by drinkingkazu** [comment]
Yes, absolutely correct and my apology for silliness...
