### ISSUE TITLE
UBWireTool.cxx not build

### ISSUE THREAD

**Issue by ruian1** [LArbys/LArCV#86]
UBWireTool does not build. Error message says that (see below)
```
UBWireTool.cxx:561:14: error: implicit instantiation of undefined template 'std::__1::array<int, 2>'
              pix_t pix;
```
It complains when calling an instantiation of pix_t while its definition looks good at line 525, 
```
 typedef std::array<int,2> pix_t;
```

**Comment by vgenty** [comment]
adding `#include <array>` at the top of the header file should fix this issue

**Comment by twongjirad** [comment]
added this header in https://github.com/LArbys/LArCV/commit/9c37c30a57fc901a46ef8628676e86848a461d37
