### ISSUE TITLE
[CRITICAL]  <MultiROICropper::process> MultiROICropper.cxx::L50 EventImage2D size 0 <= target channel 0

### ISSUE THREAD

**Issue by twongjirad** [LArbys/LArCV#88]
Running ssnet_example on tufts cluster on new tagger output.

    [NORMAL]  <IOManager::get_data> Created TTree partroi_croimerge_tree (id=24) w/ 0 entries...
    [NORMAL]  <IOManager::get_data> Created TTree image2d_tpc_tree (id=25) w/ 0 entries...
  [CRITICAL]  <MultiROICropper::process> MultiROICropper.cxx::L50 EventImage2D size 0 <= target channel 0
Traceback (most recent call last):
  File "pyana.py", line 94, in <module>
    in_proc.process_entry(event_counter,True)
TypeError: none of the 2 overloaded methods succeeded. Full details:
  bool larcv::ProcessDriver::process_entry(unsigned long entry, bool force_reload = false) =>
     (C++ exception of type larcv::larbys)
  bool larcv::ProcessDriver::process_entry() =>
    takes at most 0 arguments (2 given)
Failed with return code 256
Error occurred! cleaning...

**Comment by twongjirad** [comment]
Duh. The producer name for the images were wrong.

**Comment by drinkingkazu** [comment]
The error message is explicitly complaining about zero size image array. So I don't think it has to do with ROI for this particular error message. This is either the producer label being wrong or serious bug that made empty Image2DArray.

**Comment by vgenty** [comment]
I think the image2d producer name is wrong

`Created TTree image2d_tpc_tree...` makes me thing ssnet is looking for "tpc" producer for EventImage2D.

in `pyana_in*.cfg` I changed the image producer to run on my own input-to-tagger LArCV file

**Comment by vgenty** [comment]
dang @drinkingkazu beat me

**Comment by drinkingkazu** [comment]
ha, yes *when available* I suggest we look at complaints made from code, like we should respect compiler error/warning messages :)

**Comment by twongjirad** [comment]
heh. sorry guys, this shouldn't have been an issue. I thought I would do a better job of tracking bugs as a way to provide hints for future users. But this issue is just due to my stupidity.
