### ISSUE TITLE
error running vertex code. giving <VertexAna::process> Cannot find nearest wire for (-1,-1,-1)

### ISSUE THREAD

**Issue by twongjirad** [LArbys/LArCV#89]
This might be an issue with either my files or my running the code, but I get the following errors

file 0099
https://gist.github.com/twongjirad/486ffa320d1e3a869e0706e5597a56d9

file 0199
https://gist.github.com/twongjirad/35424ba1c330988e201c8d6761366de0

You can find the files I used to run here.

/uboone/app/users/tmw/for_vic/

sorry if this is an easy mistake. the vertex code is a black box for me right now.

**Comment by vgenty** [comment]
Thanks, will take a look once I get out of the shuttle

**Comment by vgenty** [comment]
OK I bumped LArCV here https://github.com/LArbys/dllee_unified/commit/e89c99b2415fecf67ef38fc3c3b42993dcd3b827

In summary the **image producer** in the config file did not match what's in your input file. You have the `tpc` image producer but the config is looking for `wire`. The config is hard to understand for non experts so in the code I now alert the user that they might be using the wrong producer name by checking image dimensions. Works now on your two files.

**Comment by twongjirad** [comment]
Thanks vic. 

Sorry, it was such a simple error. I thought I had replaced all the instances of wire with tpc, but clearly I didnt.

**Comment by vgenty** [comment]
No worries, I changed the required PSet parameters for three of the LArCV modules so please use the updated `prod_fullchain_ssnet_combined.cfg` as well
