### ISSUE TITLE
Running vertex container gives me this error

### ISSUE THREAD

**Issue by twongjirad** [LArbys/LArCV#93]
Running: prod_fullchain_ssnet_combined_newtag.cfg

@vgenty  and @ruian1 : this a new fcl parameter?

Traceback (most recent call last):
  File "/usr/local/share/dllee_unified/LArCV/app/LArOpenCVHandle/cfg/mac/run.py", line 12, in <module>
    proc.configure(sys.argv[1])
TypeError: none of the 2 overloaded methods succeeded. Full details:
  void larcv::ProcessDriver::configure(const string config_file) =>
    Key does not exist: "SimpleKink" (C++ exception)
  void larcv::ProcessDriver::configure(const larcv::PSet& cfg) =>
    could not convert argument 1

**Comment by ruian1** [comment]
This is a new module added by Jarrett, just need to add in the configure file with "SimpleKink : {}"
Below is the block.

trackvertexseeds: {
           ImageSetID: 1
           Verbosity : 2
           SimpleKink : {}
           ClusterHIPMIP: {
              MinHIPClusterSize: 6
              MinHIPClusterPixels: 6
              MinMIPClusterSize: 10
              MinMIPClusterPixels: 20
              MIPLevels: [10,10,10]
              HIPLevels: [70,60,40]
           }

**Comment by twongjirad** [comment]
Thanks. This fixed it.
